# Merge results

# Clear all data
rm(list=ls())
# Load in settings
source("SetUp.R")

# Name of an output file, generated by running FitAllData.R
fitsfile = "../output/RunAnalysisResults20210504T195806.csv"

# Remove 'removeOutlyingPercent'% of participants whose time to completion was too long or short:
removeOutlyingPercent = 10

fits = read.csv(fitsfile)
ppts = read.csv(pptinfo)

fits$X=NULL
fits$ParticipantIdentifier=NA
# Extract ppt id
for (j in 1:nrow(ppts)) {
    ppt = ppts[j,]
    jfit = grep(ppt$ParticipantIdentifier,fits$File)
    for (j in jfit) {
        fits$ParticipantIdentifier[j] = as.character(ppt$ParticipantIdentifier)
    }
}

results = merge(ppts,fits,by="ParticipantIdentifier")

results$Age = as.numeric(as.character(results$Age))

# Make new columns to specify low, high start and clumped/even
results$StartCondition=NA
results$StartCondition[grep("lowStart",results$Condition)]="Low"
results$StartCondition[grep("highStart",results$Condition)]="High"
results$OrderCondition=NA
results$OrderCondition[grep("clump",results$Condition)]="Clumped"
results$OrderCondition[grep("even",results$Condition)]="Even"

# Remove participants whose time to completion was unusually fast or slow:
limits = quantile(results$TimeToCompletion,c(removeOutlyingPercent/200, 1-removeOutlyingPercent/200 ))
results = filter(results,TimeToCompletion > min(limits) & TimeToCompletion <= max(limits))

write.csv(results,"../output/results.csv")


